### ISSUE TITLE
Error `make: *** No rule to make target ...` when installing in project

### ISSUE THREAD

**Issue by lucasroland** [TobiasFranek/edsdk-framework#1]
Hello, first of all thanks for your work, really appreciate.
I managed to compile the edsdk on macos with your project, but once i try to install it in my project (with `npm install ../node_packages/@dimensional/napi-canon-cameras.tgz`), I encounter this error : 

```make: *** No rule to make target `/Users/lucas/Documents/Projets/XXXX/XXXXX/node_modules/@dimensional/napi-canon-cameras/third_party/EDSDK/Framework/EDSDK.framework', needed by `Release/EDSDK.framework'.```

Do you have any idea how to fix this ?

Here's the complete log :
```bash
Lucass-MacBook-Pro:XXXXXX lucas$ npm install ./sdk-wrapper/node_packages/@dimensional/napi-canon-cameras.tgz

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> @dimensional/napi-canon-cameras@0.1.0 install /Users/lucas/Documents/Projets/XXXX/XXXXX/node_modules/@dimensional/napi-canon-cameras
> node-gyp-build

make: *** No rule to make target `/Users/lucas/Documents/Projets/XXXX/XXXXX/node_modules/@dimensional/napi-canon-cameras/third_party/EDSDK/Framework/EDSDK.framework', needed by `Release/EDSDK.framework'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/lucas/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/Users/lucas/.nvm/versions/node/v14.16.1/bin/node" "/Users/lucas/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/lucas/Documents/Projets/XXXXX/XXXXX/node_modules/@dimensional/napi-canon-cameras
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @dimensional/napi-canon-cameras@0.1.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @dimensional/napi-canon-cameras@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lucas/.npm/_logs/2022-06-14T22_10_11_508Z-debug.log
```

I saw that you forked this project from https://github.com/dimensional-de/napi-canon-cameras, and i'm not certain if you managed to make it work for macOS in the end or not.
Thank you !

**Comment by TobiasFranek** [comment]
Hi, 

did you also add the framework to your project? (should be the same folder) Otherwise i have no idea :/ unfortunately I don't know much about c++ and compiling it for node.js (This is why i forked this Repo). 

Yes this is a fork of the mentioned repository. At the moment i could not get it to work on mac os im still in contact with the canon support. This repository only exists for the support to view and analyse the Code.

I'm sorry that i could not help you more.
